name: traffic-lights-rasp
base: core22
version: '1.0.1'
summary: Raspberry pi traffic light automation
description:
  Turning on Traffic Lights with Raspberrypi and python packages

grade: stable
confinement: strict

architectures:
  - build-on: arm64
    run-on: arm64

parts:
  traffic-lights-rasp:
    plugin: python
    source: .
    requirements:
      -requirements.txt
apps:
  traffic-light-rasp:
    command: bin/main
    daemon: simple
    plugs:
      - gpio

system-usernames:
    snap_daemon: shared