name: traffic-lights-rasp
base: core20
version: '1.0.1'
summary: Raspberry pi traffic light automation
description:
  Turning on Traffic Lights with Raspberrypi and python packages

grade: devel
confinement: strict
#
#architectures:
#  - build-on: [amd64]

parts:
  traffic-lights-rasp:
    plugin: python
    source: .
#    python-requirements:
#      - /home/mats/PycharmProjects/trafficrequirements.txt
apps:
  traffic-light-rasp:
    command: bin/main
    daemon: simple
    plugs:
      - gpio

system-usernames:
    snap_daemon: shared
